### ISSUE TITLE
考虑博客加个评论功能？

### ISSUE THREAD

**Issue by liul85** [flanker/blog#11]
文章都很有启发，要不要加个评论功能方便读者讨论？

**Comment by flanker** [comment]
thanks. 

需要，同时我希望评论可以不依赖于第三方平台，即文章和评论都能够通过 github 管理起来。有啥好建议没？

**Comment by liul85** [comment]
试试这个
https://github.com/utterance/utterances

类似这样
https://github.com/draveness/blog-comments/issues?q=is%3Aissue+is%3Aclosed

**Comment by liul85** [comment]
还有这个
https://giscus.app/

**Comment by flanker** [comment]
真的是你能想到的，都有人实现了。我最后用了 https://giscus.app 前面几个都是基于 issues 的，giscus 是基于 discussions 的，看起来更符合一些。

**Comment by flanker** [comment]
<img width="1321" alt="image" src="https://user-images.githubusercontent.com/109811/178291440-0e55fcaf-835c-4fef-9151-f5ad80439ddd.png">

**Comment by liul85** [comment]
awesome!!!
